chore: update

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
   push:
     branches:
-      - master
+      - agent-master
     paths:
       - "**/*.go"
       - "go.mod"
@@ -24,70 +24,60 @@ jobs:
   build:
     strategy:
       matrix:
-        # Include amd64 on all platforms.
         goos: [linux]
-        goarch: [amd64,  arm64]
+        goarch: [amd64, arm64]
       fail-fast: false
     runs-on: ubuntu-latest
     env:
       GOOS: ${{ matrix.goos }}
       GOARCH: ${{ matrix.goarch }}
-      GOARM: ${{ matrix.goarm }}
       CGO_ENABLED: 0
     steps:
       - name: Checkout codebase
         uses: actions/checkout@v2.4.0
-      - name: Show workflow information 
+      - name: Show workflow information
         id: get_filename
         run: |
-          export _NAME=$(jq ".[\"$GOOS-$GOARCH$GOARM$GOMIPS\"].friendlyName" -r < .github/build/friendly-filenames.json)
-          echo "GOOS: $GOOS, GOARCH: $GOARCH, GOARM: $GOARM, GOMIPS: $GOMIPS, RELEASE_NAME: $_NAME"
-          echo "::set-output name=ASSET_NAME::$_NAME"
+          export _NAME=$(jq ".[\"$GOOS-$GOARCH\"].friendlyName" -r < .github/build/friendly-filenames.json)
+          echo "_NAME: $_NAME"
+          [ -z "$_NAME" ] && echo "Error: _NAME is empty" && exit 1
+          echo "GOOS: $GOOS, GOARCH: $GOARCH, RELEASE_NAME: $_NAME"
           echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV
-    
+      - name: Debug output
+        run: |
+          echo "ASSET_NAME from environment: $ASSET_NAME"
       - name: Set up Go
         uses: actions/setup-go@v2
         with:
-          go-version: 1.21.4
+          go-version: '1.21.4'
       - name: Get project dependencies
         run: go mod download
+
       - name: Build Server
         run: |
           mkdir -p build_assets
-          go build -v -o build_assets/server-vmess -trimpath -ldflags "-s -w -buildid=" ./cmd/server
+          go build -v -o build_assets/server-vmess-agent -trimpath -ldflags "-s -w" ./cmd/server-agent
       - name: Build Mips softfloat Server
         if: matrix.goarch == 'mips' || matrix.goarch == 'mipsle'
         run: |
-            GOMIPS=softfloat go build -v -o build_assets/server-vmess-softfloat -trimpath -ldflags "-s -w" ./cmd/server
+            GOMIPS=softfloat go build -v -o build_assets/server-vmess-agent-softfloat -trimpath -ldflags "-s -w" ./cmd/server-agent
       - name: Rename Windows Server
         if: matrix.goos == 'windows'
         run: |
           cd ./build_assets || exit 1
-          mv server-vmess server-vmess.exe
+          mv server-vmess-agent server-vmess-agent.exe
       - name: Prepare to release
         run: |
           cp ${GITHUB_WORKSPACE}/README.md ./build_assets/README.md
           cp ${GITHUB_WORKSPACE}/LICENSE ./build_assets/LICENSE
-          LIST=('geoip geoip geoip' 'domain-list-community dlc geosite')
-          for i in "${LIST[@]}"
-          do
-            INFO=($(echo $i | awk 'BEGIN{FS=" ";OFS=" "} {print $1,$2,$3}'))
-            LASTEST_TAG="$(curl -sL "https://api.github.com/repos/v2fly/${INFO[0]}/releases" | jq -r ".[0].tag_name" || echo "latest")"
-            FILE_NAME="${INFO[2]}.dat"
-            echo -e "Downloading ${FILE_NAME}..."
-            curl -L "https://github.com/v2fly/${INFO[0]}/releases/download/${LASTEST_TAG}/${INFO[1]}.dat" -o ./build_assets/${FILE_NAME}
-            echo -e "Verifying HASH key..."
-            HASH="$(curl -sL "https://github.com/v2fly/${INFO[0]}/releases/download/${LASTEST_TAG}/${INFO[1]}.dat.sha256sum" | awk -F ' ' '{print $1}')"
-            [ "$(sha256sum "./build_assets/${FILE_NAME}" | awk -F ' ' '{print $1}')" == "${HASH}" ] || { echo -e "The HASH key of ${FILE_NAME} does not match cloud one."; exit 1; }
-          done
       - name: Create ZIP archive
         shell: bash
         run: |
           pushd build_assets || exit 1
           touch -mt $(date +%Y01010000) *
-          zip -9vr ../server-vmess-$ASSET_NAME.zip .
+          zip -9vr ../server-vmess-agent-$ASSET_NAME.zip .
           popd || exit 1
-          FILE=./server-vmess-$ASSET_NAME.zip
+          FILE=./server-vmess-agent-$ASSET_NAME.zip
           DGST=$FILE.dgst
           for METHOD in {"md5","sha1","sha256","sha512"}
           do
@@ -95,19 +85,21 @@ jobs:
           done
       - name: Change the name
         run: |
-          mv build_assets server-vmess-$ASSET_NAME
+          mv build_assets server-vmess-agent-$ASSET_NAME
+      # Upload to artifacts
+
       - name: Upload files to Artifacts
         uses: actions/upload-artifact@v2
         with:
-          name: server-vmess-${{ steps.get_filename.outputs.ASSET_NAME }}
+          name: server-vmess-agent-${{ env.ASSET_NAME }}
           path: |
-            ./server-vmess-${{ steps.get_filename.outputs.ASSET_NAME }}/*
+            ./server-vmess-agent-${{ env.ASSET_NAME }}
+      # Upload binaries to release
       - name: Upload binaries to release
         uses: svenstaro/upload-release-action@v2
         if: github.event_name == 'release'
         with:
-          repo_token: ${{secrets.GITHUB_TOKEN}}
-          file: ./server-vmess-${{ steps.get_filename.outputs.ASSET_NAME }}.zip*
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
+          file: ./server-vmess-agent-${{ env.ASSET_NAME }}.zip*
           tag: ${{ github.ref }}
           file_glob: true
-         
